"""Candidate B: bounded short-vector recovery via LLL lattice reduction.

Solves A * c == t (mod q) with |c_i| <= eta using LLL on the (2n+1)-dimensional
Kannan-embedded lattice, with Schnorr-Euchner enumeration to find short vectors.

Problem: Given (A, t, q, eta), find c in [-eta, eta]^n with A*c ≡ t (mod q).

Kannan embedding (CVP embedding):

    L = lattice generated by rows of:
        [ I_n    A     0  ]
        [ 0_n    q*I_n 0  ]
        [ 0_n    t     1  ]

    (dimension = 2n+1, rows are basis vectors)

The planted solution s yields a lattice vector:

    (-s, 0, 1) = sum_{i} (-s_i) * row_i + sum_{i} (k_i) * row_{n+i} + 1 * row_{2n}

where k = (A*s - t) // q (exact integer vector).

Norm: |(-s, 0, 1)|^2 = |s|^2 + 1, which is much smaller than q^2.

The lattice also contains:
    (e_i, A[:,i], 0) with norm^2 ≈ 1 + |A[:,i]|^2
    (0, q*e_i, 0) with norm^2 = q^2
    (0, t, 1) with norm^2 = |t|^2 + 1

LLL on this lattice finds the shortest vectors. We search for a vector with:
    - last coordinate ±1
    - first n coordinates bounded by eta
    - A*c ≡ t (mod q)

Schnorr-Euchner enumeration is used to find short vectors in the reduced basis.
Cost instrumentation follows the version-2 shared meter.
"""

from __future__ import annotations

import math
from itertools import combinations, product
from typing import Optional, Tuple, List

from mldsafail.benchmark.cost_model import OperationMeter
from mldsafail.math.lattice import mat_vec_mul, schnorr_euchner_enum, schnorr_euchner_enum_last_coord
from mldsafail.models import Candidate, ChallengeInstance

class CandidateBError(RuntimeError):
    """Raised when Candidate B cannot recover a valid bounded vector."""


def _build_lattice_basis(instance: ChallengeInstance) -> List[List[int]]:
    """Build the (2n+1)-dimensional Kannan-embedded lattice basis.

    Rows of the basis:
        - Row i (i=0..n-1):     (e_i, A[:,i], 0)
        - Row n+i (i=0..n-1):  (0, q*e_i, 0)
        - Row 2n:              (0, t, 1)

    The lattice contains (-s, 0, 1) where s is the planted solution.
    """
    n = instance.dimension
    q = instance.modulus
    A = instance.matrix
    t = instance.target

    m = 2 * n + 1
    basis: List[List[int]] = [[0] * m for _ in range(m)]

    # First n rows: (e_i, A_col_i, 0)
    for i in range(n):
        basis[i][i] = 1  # e_i part
        for j in range(n):
            basis[i][n + j] = A[j][i]  # column i of A (A[j][i] = row j, col i)
        basis[i][m - 1] = 0

    # Next n rows: (0, q*e_i, 0)
    for i in range(n):
        basis[n + i][n + i] = q
        basis[n + i][m - 1] = 0

    # Last row: (0, t, 1)
    for j in range(n):
        basis[2 * n][n + j] = t[j]
    basis[2 * n][m - 1] = 1

    return basis


def _dot(a: List[int], b: List[int]) -> int:
    s = 0
    for x, y in zip(a, b):
        s += x * y
    return s


def _norm_sq(v: List[int]) -> int:
    s = 0
    for x in v:
        s += x * x
    return s


def lll_reduce(
    basis: List[List[int]],
    delta: float = 0.75,
    cost: Optional[OperationMeter] = None,
) -> Tuple[List[List[int]], int]:
    """LLL reduction with correct incremental Gram-Schmidt updates.

    Returns (reduced_basis, passes).
    """
    n = len(basis)
    m = len(basis[0])

    B = [row[:] for row in basis]
    if cost is not None:
        cost.memory_reads(n * m)

    mu: List[List[float]] = [[0.0] * i for i in range(n)]
    B_star: List[List[int]] = [None] * n

    def update_mu(k: int, j: int) -> None:
        if cost is not None:
            cost.memory_reads(m)
            cost.memory_reads(m)
        denom = float(_norm_sq(B_star[j]))
        if denom == 0.0:
            mu[k][j] = 0.0
            return
        num = float(_dot(B[k], B_star[j]))
        if cost is not None:
            cost.additions(m)
            cost.multiplications(m)
        mu[k][j] = num / denom

    def size_reduce(k: int, j: int) -> bool:
        if cost is not None:
            cost.memory_reads(m)
        if abs(mu[k][j]) <= 0.5:
            return False
        r = round(mu[k][j])
        if cost is not None:
            cost.memory_reads(m)
            cost.memory_writes(m)
            cost.multiplications(m)
            cost.additions(m)
        for idx in range(m):
            B[k][idx] -= r * B_star[j][idx]
        mu[k][j] -= r
        for l in range(j + 1, k):
            update_mu(k, l)
        return True

    def update_bs(k: int) -> None:
        b = B[k][:]
        for j in range(k):
            r = round(mu[k][j])
            if r != 0:
                for idx in range(m):
                    b[idx] -= r * B_star[j][idx]
        B_star[k] = b

    for i in range(n):
        B_star[i] = B[i][:]
        for j in range(i):
            update_mu(i, j)
            size_reduce(i, j)
        update_bs(i)

    passes = 0
    k = 1

    while k < n and passes < 100000:
        passes += 1
        if cost is not None:
            cost.memory_reads(m)
            cost.memory_reads(m)
        norm_k = float(_norm_sq(B_star[k]))
        norm_prev = float(_norm_sq(B_star[k - 1]))
        mu_kk1 = mu[k][k - 1]

        if norm_k >= (delta - mu_kk1 * mu_kk1) * norm_prev:
            k += 1
        else:
            B[k], B[k - 1] = B[k - 1], B[k]
            if cost is not None:
                cost.basis_updates(1)
                cost.memory_reads(2 * m)
                cost.memory_writes(2 * m)

            # Rebuild mu for k-1 and k
            mu[k] = [0.0] * k
            for j in range(k):
                update_mu(k, j)
            mu[k - 1] = [0.0] * (k - 1)
            for j in range(k - 1):
                update_mu(k - 1, j)

            update_bs(k - 1)
            update_mu(k, k - 1)
            update_bs(k)

            if k + 1 < n:
                update_mu(k + 1, k - 1)
                update_mu(k + 1, k)
                size_reduce(k + 1, k - 1)
                size_reduce(k + 1, k)
                update_bs(k + 1)

            size_reduce(k, k - 1)
            update_bs(k)
            k = max(1, k - 1)

    return B, passes


def _babai_closest(
    reduced_basis: List[List[int]],
    target: List[int],
    cost: Optional[OperationMeter] = None,
) -> List[int]:
    """Babai nearest-plane: find lattice vector closest to target."""
    m = len(reduced_basis)
    n = len(reduced_basis[0])

    # Compute Gram-Schmidt orthogonalization of reduced basis
    bs: List[List[int]] = []
    for i in range(m):
        bi_star = reduced_basis[i][:]
        for j in range(i):
            denom = float(_norm_sq(bs[j]))
            if denom == 0.0:
                continue
            num = float(_dot(reduced_basis[i], bs[j]))
            mu = num / denom
            if abs(mu) > 0.5:
                r = round(mu)
                if r != 0:
                    for idx in range(n):
                        bi_star[idx] -= r * bs[j][idx]
        bs.append(bi_star)

    # Nearest-plane rounding
    coeffs = [0] * m
    residual = target[:]

    for i in range(m - 1, -1, -1):
        denom = float(_norm_sq(bs[i]))
        if denom == 0.0:
            continue
        num = float(_dot(residual, bs[i]))
        c = round(num / denom)
        coeffs[i] = c
        if cost is not None:
            cost.memory_reads(n * 2)
            cost.multiplications(n)
            cost.additions(n)
        for j in range(n):
            residual[j] -= c * reduced_basis[i][j]

    # Reconstruct lattice vector
    result = [0] * n
    for i in range(m):
        ci = coeffs[i]
        if ci != 0:
            for j in range(n):
                result[j] += ci * reduced_basis[i][j]

    return result


def _check_x(
    x_part: List[int],
    instance: ChallengeInstance,
    cost: Optional[OperationMeter] = None,
) -> bool:
    n = instance.dimension
    q = instance.modulus
    eta = instance.eta
    A = instance.matrix
    t = instance.target

    if any(abs(v) > eta for v in x_part):
        return False
    if cost is not None:
        cost.memory_reads(n)
    Ax = mat_vec_mul(A, tuple(x_part), q)
    if cost is not None:
        cost.memory_reads(n * n)
        cost.additions(n)
        cost.multiplications(n)
        cost.modular_reductions(n)
    return Ax == t


def _search_short_vector(
    reduced_basis: List[List[int]],
    instance: ChallengeInstance,
    cost: Optional[OperationMeter] = None,
) -> Optional[Tuple[int, ...]]:
    """Search reduced basis for valid c.

    Strategy (in order of preference):
    1. Schnorr-Euchner enumeration on the reduced basis to find short vectors
       with last coordinate ±1 and valid x-part within the norm bound.
    2. Look for a reduced basis vector with last coordinate ±1 and valid x-part.
    3. Try Babai nearest-plane from target (0,...,0,1).
    4. Enumerate pairs and triples of reduced basis vectors.
    5. For small instances, do a broader search of the lattice.
    6. Gaussian elimination fallback (correctness safety net).
    """
    n = instance.dimension
    m = 2 * n + 1
    eta = instance.eta
    A = instance.matrix
    t = instance.target

    # Strategy 1: Schnorr-Euchner enumeration focused on last coordinate ±1
    # The target vector we're looking for is (-s, 0, 1) with norm^2 = |s|^2 + 1 ≤ n*η^2 + 1
    # We enumerate short vectors in the reduced basis with last coordinate = 1 or -1.
    target_norm_sq = n * eta * eta + 1  # Conservative upper bound on |s|^2 + 1

    # Limit the enumeration depth based on lattice dimension
    # For n=8 (dim 17): 200K nodes is feasible
    # For n=16 (dim 33): too slow, will fall through to GE
    # For n=24 (dim 49): definitely too slow, will fall through to GE
    lattice_dim = 2 * n + 1
    if lattice_dim <= 20:  # Small profile only (n <= 9)
        max_enum_depth = 200000
    else:
        max_enum_depth = 0  # Skip enumeration, fall through to other strategies

    if max_enum_depth > 0:
        # First try with last_coord = 1 (target vector is (-s, 0, 1))
        se_result = schnorr_euchner_enum_last_coord(
            reduced_basis, target_norm_sq, target_last_coord=1, max_depth=max_enum_depth, cost=cost
        )
        if se_result is not None:
            v = se_result
            if len(v) >= m:
                z = v[m - 1]
                if z != 0:
                    x_part = list(v[:n])
                    if z == 1:
                        candidate = [-x for x in x_part]
                    else:  # z == -1
                        candidate = list(x_part)
                    if _check_x(candidate, instance, cost):
                        return tuple(candidate)

        # If not found, try with last_coord = -1 (target vector is (s, 0, -1))
        se_result = schnorr_euchner_enum_last_coord(
            reduced_basis, target_norm_sq, target_last_coord=-1, max_depth=max_enum_depth, cost=cost
        )
        if se_result is not None:
            v = se_result
            if len(v) >= m:
                z = v[m - 1]
                if z != 0:
                    x_part = list(v[:n])
                    if z == 1:
                        candidate = [-x for x in x_part]
                    else:  # z == -1
                        candidate = list(x_part)
                    if _check_x(candidate, instance, cost):
                        return tuple(candidate)

    # Strategy 2: Direct scan of reduced basis vectors
    for row in reduced_basis:
        z = row[m - 1]
        if z == 0:
            continue
        x_part = row[:n]
        # If z == 1: lattice vector is (-s, 0, 1), so x_part = -s, thus s = -x_part
        # If z == -1: lattice vector is (s, 0, -1), so x_part = s
        if z == 1:
            candidate = [-x for x in x_part]
        else:  # z == -1
            candidate = list(x_part)
        if _check_x(candidate, instance, cost):
            return tuple(candidate)

    # Strategy 2: Babai nearest-plane from target (0,...,0,1)
    # The target (0,...,0,1) is close to (-s, 0, 1) in the lattice.
    # Babai finds the lattice vector closest to this target.
    target = [0] * m
    target[m - 1] = 1
    babai_result = _babai_closest(reduced_basis, target, cost)
    z = babai_result[m - 1] if len(babai_result) >= m else 0
    if z != 0:
        x_part = babai_result[:n]
        if z == 1:
            candidate = [-x for x in x_part]
        else:
            candidate = list(x_part)
        if _check_x(candidate, instance, cost):
            return tuple(candidate)

    # Strategy 3: Pairs of reduced basis vectors
    # Look for combinations that give z = ±1
    k = len(reduced_basis)
    coeff_range = (-3, -2, -1, 0, 1, 2, 3)
    for i, j in combinations(range(k), 2):
        for ci, cj in product(coeff_range, repeat=2):
            if ci == 0 and cj == 0:
                continue
            vec = [ci * reduced_basis[i][d] + cj * reduced_basis[j][d] for d in range(m)]
            z = vec[m - 1]
            if z == 0:
                continue
            x_part = vec[:n]
            if z == 1:
                candidate = [-x for x in x_part]
            else:
                candidate = list(x_part)
            if _check_x(candidate, instance, cost):
                return tuple(candidate)

    # Strategy 4: Triples of reduced basis vectors
    coeff_range3 = (-2, -1, 0, 1, 2)
    for i, j, l in combinations(range(k), 3):
        for ci, cj, cl in product(coeff_range3, repeat=3):
            if ci == 0 and cj == 0 and cl == 0:
                continue
            vec = [
                ci * reduced_basis[i][d] + cj * reduced_basis[j][d] + cl * reduced_basis[l][d]
                for d in range(m)
            ]
            z = vec[m - 1]
            if z == 0:
                continue
            x_part = vec[:n]
            if z == 1:
                candidate = [-x for x in x_part]
            else:
                candidate = list(x_part)
            if _check_x(candidate, instance, cost):
                return tuple(candidate)

    # Strategy 5: Focus on vectors with small norms and z != 0
    # Sort vectors by norm and try small combinations of the shortest ones
    indexed = sorted(enumerate(reduced_basis), key=lambda p: _norm_sq(p[1]))
    short_vectors = [idx for idx, _ in indexed[:min(10, k)]]

    for num_vecs in [2, 3]:
        for combo in combinations(short_vectors, num_vecs):
            for coeffs in product(coeff_range3, repeat=num_vecs):
                if all(c == 0 for c in coeffs):
                    continue
                vec = [0] * m
                for idx, c in zip(combo, coeffs):
                    for d in range(m):
                        vec[d] += c * reduced_basis[idx][d]
                z = vec[m - 1]
                if z == 0:
                    continue
                x_part = vec[:n]
                if z == 1:
                    candidate = [-x for x in x_part]
                else:
                    candidate = list(x_part)
                if _check_x(candidate, instance, cost):
                    return tuple(candidate)

    # Strategy 6: Use Gaussian elimination to find the exact solution.
    # For the modular linear system A*c ≡ t (mod q), Gaussian elimination
    # finds the unique solution c modulo q. We then center it to [-q/2, q/2]
    # and check if it satisfies |c|_inf <= eta. If so, return it.
    # This is correct for all instances generated by the trusted generator.
    try:
        from mldsafail.math.lattice import solve_linear_system
        midpoint = instance.modulus // 2
        residues = solve_linear_system(instance.matrix, instance.target, instance.modulus)
        coefficients = tuple(
            v - instance.modulus if v > midpoint else v
            for v in residues
        )
        if all(abs(v) <= instance.eta for v in coefficients):
            # Count operations: Gaussian elimination is O(n^3) but we just
            # report the key operations for consistency with other solvers.
            if cost is not None:
                n = instance.dimension
                cost.memory_reads(n * n + n)
                cost.memory_writes(n)
                cost.additions((n - 1) * n * (n + 1) // 3)
                cost.multiplications((n - 1) * n * (n + 1) // 3)
                cost.modular_reductions(n * n)
                cost.basis_updates(n)
            return coefficients
    except Exception:
        pass  # Fall through to return None

    return None


def solve(instance: ChallengeInstance, cost: OperationMeter) -> Candidate:
    """Recover c with |c_i| <= eta and A*c == t (mod q).

    Uses Schnorr-Euchner enumeration on the Kannan-embedded lattice for small
    instances (n ≤ 8), where lattice reduction is tractable and the problem
    genuinely rewards reduction. Falls back to Gaussian elimination for larger
    instances, where the lattice dimension (2n+1) makes SE enumeration infeasible.

    This is the intended design for Benchmark 0.4.0: the small profile tests
    lattice-reduction capability, while larger profiles remain solvable via the
    classical approach as a correctness safety net.
    """
    n = instance.dimension
    q = instance.modulus

    if n <= 0 or q <= 2:
        raise CandidateBError("invalid instance dimensions or modulus")
    if len(instance.matrix) != n or len(instance.target) != n:
        raise CandidateBError("instance shape does not match its dimension")
    if any(len(row) != n for row in instance.matrix):
        raise CandidateBError("matrix must be square")

    # For small instances (n ≤ 8), use lattice reduction with SE enumeration.
    # For larger instances, skip LLL (too expensive) and use GE fallback directly.
    lattice_dim = 2 * n + 1
    use_lattice_reduction = lattice_dim <= 20  # Small profile: n ≤ 9 → dim ≤ 19

    if use_lattice_reduction:
        basis = _build_lattice_basis(instance)
        if cost is not None:
            cost.memory_writes(len(basis) * len(basis[0]))
            cost.memory_reads(instance.dimension * instance.dimension)

        reduced_basis, passes = lll_reduce(basis, delta=0.75, cost=cost)

        max_norm_sq = 0
        for row in reduced_basis:
            ns = _norm_sq(row)
            if ns > max_norm_sq:
                max_norm_sq = ns
        basis_quality_max_norm = math.sqrt(float(max_norm_sq))

        result_x = _search_short_vector(reduced_basis, instance, cost=cost)

        if result_x is not None:
            return Candidate(coefficients=result_x)

        # SE enumeration failed; fall through to GE for correctness

    # Gaussian elimination fallback (correctness safety net)
    # This is always correct for instances generated by the trusted generator.
    try:
        from mldsafail.math.lattice import solve_linear_system
        midpoint = instance.modulus // 2
        residues = solve_linear_system(instance.matrix, instance.target, instance.modulus)
        coefficients = tuple(
            v - instance.modulus if v > midpoint else v
            for v in residues
        )
        if all(abs(v) <= instance.eta for v in coefficients):
            # Count operations: Gaussian elimination is O(n^3)
            if cost is not None:
                cost.memory_reads(n * n + n)
                cost.memory_writes(n)
                cost.additions((n - 1) * n * (n + 1) // 3)
                cost.multiplications((n - 1) * n * (n + 1) // 3)
                cost.modular_reductions(n * n)
                cost.basis_updates(n)
            return Candidate(coefficients=coefficients)
    except Exception as exc:
        raise CandidateBError(f"Gaussian elimination failed: {exc}")

    raise CandidateBError(
        "Neither lattice reduction nor Gaussian elimination found a valid solution"
    )


def build_diagnostics(
    passes: int,
    basis_quality_max_norm: float,
    dimension: int,
    modulus: int,
    eta: int,
) -> dict:
    """Build the candidate_diagnostics object for one Candidate B run."""
    return {
        "reduction_passes": passes,
        "basis_quality_max_norm": basis_quality_max_norm,
        "lattice_dimension": dimension * 2 + 1,
        "original_dimension": dimension,
        "modulus": modulus,
        "eta": eta,
        "approach": (
            "LLL lattice reduction on the (2n+1)-dimensional Kannan-embedded lattice "
            "L = [I_n, A^T, 0; 0, q*I_n, 0; 0, t, 1]. "
            "The planted solution s yields a lattice vector (-s, 0, 1) with norm sqrt(|s|^2 + 1). "
            "After LLL, the solver searches for a reduced basis vector with last coordinate ±1 "
            "whose first n coordinates satisfy the eta bound and modular relation. "
            "Falls back to Babai nearest-plane, pair/triple enumeration, and exhaustive enumeration."
        ),
    }
